### ISSUE TITLE
Ability to switch regions?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#35]
Hi,

After I experienced #34, IronMQ support folks said:

```
Still investigating here.
If you would like to post to another region in the meanwhile that should suffice as a temporary fix until US-EAST comes back completely.
```

I don't see a way to switch regions in this library, please advise, thanks.

**Comment by featalion** [comment]
By the "post to another region" it means just another IronMQ server. All you need to do is to change configuration of the client. See available cloud regions [there](http://dev.iron.io/mq/reference/clouds/)

**Comment by GeoffreyPlitt** [comment]
Yeah that's the same understanding I had. What I'm saying is, I don't see how to switch hosts using your library. I see https://github.com/iron-io/iron_mq_node/blob/master/src/api_client.coffee has hardcoded values. Perhaps we can get a constructor option that takes a hostname?

**Comment by featalion** [comment]
`APIClient` extends [`IronCore.Client`](https://github.com/iron-io/iron_core_node/blob/master/src/client.coffee). IronCore libraries follow rules inherited from [this document](http://dev.iron.io/mq/reference/configuration/). So that, it loads configuration from `~/.iron.json`, `path-to-project/iron.json`, and environment variables. `IronCore.Client` merges loaded config with `defaultOptions`, overwriting them. Then it merges result with `options`, which passed to constructor. Options, which is passed to constructor, have the highest priority (rewrites defaults, configuration files, envs, etc. configuration).

**Comment by GeoffreyPlitt** [comment]
Gotcha, looks like it's all there and I just didn't quite see it, thanks!
